"""empty message

Revision ID: c5f1d85745fc
Revises: ed8979a66bd6
Create Date: 2023-10-30 20:31:11.420956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5f1d85745fc'
down_revision = 'ed8979a66bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=64), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
